# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

f <- function(x) {
    .Call('RcppBrent_f', PACKAGE = 'RcppBrent', x)
}

min_f <- function() {
    .Call('RcppBrent_min_f', PACKAGE = 'RcppBrent')
}

